import { Lead, Delivery, TimelineEvent, TeamMember, ConversationThread, FleetVehicle, ConsultantCapacity } from './types';

export const ASSET_PATHS = {
  officialBrand: '/images/official-byd-melbourne-cbd-lockup.webp',
  officialBrandPng: '/images/official-byd-melbourne-cbd-lockup.png',
  hero: '/images/byd-showroom-hero.webp',
  delivery: '/images/byd-delivery-bay.jpg',
  consultant: '/images/byd-consultant-showroom.jpg',
  testDrive: '/images/byd-test-drive-ready.jpg',
  ogImage: '/images/og-image.png',
};

export const INITIAL_LEADS: Lead[] = [
  {
    id: 1,
    name: 'Sarah Mitchell',
    initials: 'SM',
    model: 'SEALION 7 Premium',
    score: 86,
    stage: 'Qualified',
    source: 'Carsales',
    lastTouch: 'Inbound SMS · 8 min ago',
    action: 'Reply now',
    priority: true,
    consultant: 'Alex Morgan',
    phone: '+61 412 890 234',
    email: 'sarah.m@example.com',
    notes: 'Interested in SEALION 7 Premium in Atlantis Grey. Trade-in: 2019 Mazda CX-5. Test drive confirmed for 9:00 AM.',
  },
  {
    id: 2,
    name: 'Daniel Cho',
    initials: 'DC',
    model: 'SEAL Premium',
    score: 74,
    stage: 'Engaged',
    source: 'Web',
    lastTouch: 'Brochure sent · 42 min ago',
    action: 'Book drive',
    consultant: 'Alex Morgan',
    phone: '+61 433 129 881',
    email: 'daniel.cho@example.com',
    notes: 'Comparing Novated Lease vs standard finance on SEAL Premium. Follow-up call scheduled 2:15 PM.',
  },
  {
    id: 3,
    name: 'Priya Nair',
    initials: 'PN',
    model: 'ATTO 3 Extended',
    score: 68,
    stage: 'Committed',
    source: 'Walk-in',
    lastTouch: 'Deposit received · Yesterday',
    action: 'View delivery',
    consultant: 'Alex Morgan',
    phone: '+61 401 552 901',
    email: 'priya.nair@example.com',
    notes: 'Vehicle arrived at Melbourne CBD showroom. Handover ready in Delivery Bay 2 at 10:30 AM.',
  },
  {
    id: 4,
    name: 'Tom Williams',
    initials: 'TW',
    model: 'SHARK 6',
    score: 59,
    stage: 'Imported',
    source: 'Autogate',
    lastTouch: 'Allocated · 1 hr 54 min ago',
    action: 'Make first touch',
    priority: true,
    phone: '+61 422 710 449',
    email: 'twilliams@example.com',
    notes: 'New import from Autogate lead feed. High interest in SHARK 6 Dual-Cab PHEV ute.',
  },
  {
    id: 5,
    name: 'Mia Roberts',
    initials: 'MR',
    model: 'DOLPHIN Premium',
    score: 52,
    stage: 'Engaged',
    source: 'Phone',
    lastTouch: 'Call logged · Yesterday',
    action: 'Send follow-up',
    consultant: 'Lena Park',
    phone: '+61 419 663 208',
    email: 'mia.roberts@example.com',
    notes: 'Looking for urban commuter. Requested color swatch confirmation for Coral Pink.',
  },
  {
    id: 6,
    name: 'Liam Bennett',
    initials: 'LB',
    model: 'SEALION 7 Premium',
    score: 91,
    stage: 'Committed',
    source: 'Referral',
    lastTouch: 'Finance approved · 2 hrs ago',
    action: 'Track handover',
    consultant: 'Noah White',
    phone: '+61 411 902 443',
    email: 'l.bennett@example.com',
    notes: 'Pre-delivery inspection underway in preparation for Wednesday handover.',
  },
  {
    id: 7,
    name: 'Emma Liu',
    initials: 'EL',
    model: 'DOLPHIN Premium',
    score: 64,
    stage: 'Committed',
    source: 'Web Campaign',
    lastTouch: 'Transit notification · 3 hrs ago',
    action: 'Prepare PDI',
    consultant: 'Sophie Tran',
    phone: '+61 430 771 992',
    email: 'emma.liu@example.com',
    notes: 'Vehicle en route from Port Melbourne holding yard.',
  },
];

export const INITIAL_DELIVERIES: Delivery[] = [
  {
    id: 1,
    name: 'Priya Nair',
    vehicle: 'ATTO 3 Extended · Ski White',
    date: 'Mon 8 Sep · 10:30',
    stage: 'Ready for Pickup',
    status: 'Contacted',
    rego: '1BX 7QF',
    vin: '…843921',
    agent: 'Sophie Tran',
  },
  {
    id: 2,
    name: 'Liam Bennett',
    vehicle: 'SEALION 7 Premium · Atlantis Grey',
    date: 'Wed 10 Sep · 14:00',
    stage: 'PDI',
    status: 'Not contacted',
    rego: 'Pending',
    vin: '…115728',
    agent: 'Noah White',
  },
  {
    id: 3,
    name: 'Emma Liu',
    vehicle: 'DOLPHIN Premium · Coral Pink',
    date: 'Fri 12 Sep · 09:00',
    stage: 'In Transit',
    status: 'Contacted',
    rego: 'Pending',
    vin: '…620184',
    agent: 'Sophie Tran',
  },
];

export const TODAY_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    time: '09:00',
    end: '09:45',
    title: 'Test drive · Sarah Mitchell',
    detail: 'SEALION 7 · Demo loop B',
    type: 'drive',
  },
  {
    time: '10:30',
    end: '11:30',
    title: 'Delivery · Priya Nair',
    detail: 'Delivery bay 2 · locked',
    type: 'delivery',
  },
  {
    time: '12:30',
    end: '13:00',
    title: 'Personal hold',
    detail: 'Lunch',
    type: 'hold',
  },
  {
    time: '14:15',
    end: '14:30',
    title: 'Follow-up · Daniel Cho',
    detail: 'Finance comparison',
    type: 'followup',
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    name: 'Alex Morgan',
    role: 'Senior EV Specialist',
    avatar: 'AM',
    load: 72,
    events: [
      { start: 10, width: 15, title: 'Drive: S. Mitchell', type: 'drive' },
      { start: 30, width: 20, title: 'Delivery: P. Nair', type: 'delivery' },
      { start: 68, width: 10, title: 'Call: D. Cho', type: 'followup' },
    ],
  },
  {
    name: 'Lena Park',
    role: 'Product Consultant',
    avatar: 'LP',
    load: 46,
    events: [
      { start: 20, width: 15, title: 'Drive: M. Roberts', type: 'drive' },
      { start: 50, width: 15, title: 'Floor duty', type: 'hold' },
    ],
  },
  {
    name: 'Sophie Tran',
    role: 'Handover Specialist',
    avatar: 'ST',
    load: 88,
    events: [
      { start: 28, width: 22, title: 'Priya N. Handover', type: 'delivery' },
      { start: 55, width: 18, title: 'PDI Pre-check', type: 'hold' },
      { start: 75, width: 15, title: 'Client Sync', type: 'followup' },
    ],
  },
  {
    name: 'Noah White',
    role: 'Commercial Lead',
    avatar: 'NW',
    load: 61,
    events: [
      { start: 15, width: 20, title: 'Fleet Presentation', type: 'drive' },
      { start: 60, width: 15, title: 'Autogate Sync', type: 'followup' },
    ],
  },
];

export const CONVERSATION_THREADS: ConversationThread[] = [
  {
    id: 1,
    name: 'Sarah Mitchell',
    initials: 'SM',
    lastMessage: 'Thanks Alex — 9am works. Do I need to bring anything besides my licence?',
    time: '8 min ago',
    unreadCount: 1,
    model: 'SEALION 7 Premium',
  },
  {
    id: 2,
    name: 'Daniel Cho',
    initials: 'DC',
    lastMessage: 'Got the novated lease estimate. Let’s review during the call this afternoon.',
    time: '42 min ago',
    model: 'SEAL Premium',
  },
  {
    id: 3,
    name: 'Priya Nair',
    initials: 'PN',
    lastMessage: 'On my way to Elizabeth St! Looking forward to picking up the ATTO 3.',
    time: '1 hr ago',
    model: 'ATTO 3 Extended',
  },
  {
    id: 4,
    name: 'Tom Williams',
    initials: 'TW',
    lastMessage: 'Enquiry received: Interested in payload specs and charging times on SHARK 6.',
    time: '2 hrs ago',
    unreadCount: 1,
    model: 'SHARK 6',
  },
  {
    id: 5,
    name: 'Mia Roberts',
    initials: 'MR',
    lastMessage: 'Can you verify if the Dolphin Premium in Coral Pink has the two-tone roof option?',
    time: 'Yesterday',
    model: 'DOLPHIN Premium',
  },
];

export const FLEET_VEHICLES: FleetVehicle[] = [
  {
    id: 'DEMO-01',
    model: 'SEALION 7 Premium',
    plate: 'BYD 007',
    battery: '94%',
    status: 'Ready',
    location: 'Bay 1',
  },
  {
    id: 'DEMO-02',
    model: 'SEAL Premium (AWD)',
    plate: 'BYD 002',
    battery: '88%',
    status: 'Ready',
    location: 'Bay 3',
  },
  {
    id: 'DEMO-03',
    model: 'ATTO 3 Extended',
    plate: 'BYD 003',
    battery: '98%',
    status: 'Ready',
    location: 'Charging Post 2',
  },
];

export const CONSULTANT_CAPACITIES: ConsultantCapacity[] = [
  {
    id: 'AM',
    name: 'Alex Morgan',
    initials: 'AM',
    leadsCount: 8,
    capacityPct: 72,
    status: 'Optimal Floor Load',
  },
  {
    id: 'LP',
    name: 'Lena Park',
    initials: 'LP',
    leadsCount: 5,
    capacityPct: 46,
    status: 'Capacity Available',
  },
  {
    id: 'NW',
    name: 'Noah White',
    initials: 'NW',
    leadsCount: 7,
    capacityPct: 61,
    status: 'Optimal Floor Load',
  },
  {
    id: 'ST',
    name: 'Sophie Tran',
    initials: 'ST',
    leadsCount: 11,
    capacityPct: 92,
    status: 'Near Full Capacity',
    warning: 'Delivery schedule dense today (3 handovers). Recommend routing new leads to Lena or Alex.',
  },
];

export const PERFORMANCE_CHART_DATA = [54, 63, 49, 74, 68, 82, 76];
export const PERFORMANCE_CHART_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

export const QUICK_TEMPLATES = [
  {
    label: 'Test Drive Confirmation',
    text: 'Hi [Name], your test drive for the [Model] at BYD Melbourne CBD (360 Elizabeth St) is confirmed for [Time]. Looking forward to seeing you. — Alex Morgan',
  },
  {
    label: 'Delivery Readiness',
    text: 'Hi [Name], fantastic news! Your [Model] is fully prepped and sparkling in Delivery Bay 2. See you at [Time] for handover. — Alex Morgan',
  },
  {
    label: 'Quote & Novated Lease Follow-up',
    text: 'Hi [Name], following up on our conversation regarding the [Model]. I have prepared the tailored novated lease comparison for you. Let me know when suits for a quick call. — Alex Morgan',
  },
  {
    label: 'First Touch Introduction',
    text: 'Hi [Name], thank you for enquiring about the BYD [Model] with BYD Melbourne CBD. I would love to answer any questions or arrange a private demonstration drive. — Alex Morgan',
  },
];
